name: Build

on:
  push:
    branches: [ master, muth/ci-fixes ]
  pull_request:
    branches: [ master ]

  # Manual trigger.
  # See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install missing programs for tests
      run: |
        sudo apt-get update
        sudo apt-get install emacs screen tcsh zsh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make tests
      run: make tests
    - name: make check
      run: ./test/autotest.py --retry-once
